from selenium.webdriver.common.by import By


class ELKSearchLocator:
    go_with_password_button_locator = (By.XPATH, '//button[@id="standard_auth_btn"]')
    header_child_locator = (By.XPATH, '//header[@id="app-header"]//child::div[1]//child::div[1]')
    logo_locator = (By.XPATH, '//div[@class="main-header__logo-container"]')
    email_tab_locator = (By.ID, 't-btn-tab-mail')
    login_tab_locator = (By.ID, 't-btn-tab-login')
    phone_tab_locator = (By.ID, 't-btn-tab-phone')
    personal_account_tab_locator = (By.ID, 't-btn-tab-ls')
    phone_field_locator = (By.XPATH, '//input[@id="username"]//following::span')
    password_name_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    login_button_locator = (By.XPATH, '//button[@id="kc-login"]')
    login_otp_button_locator = (By.XPATH, '//button[@id="back_to_otp_btn"]')
    user_agreement_link_locator = (By.XPATH, '//div[@class="auth-policy"]//child::a')
    registration_link_locator = (By.ID, 'kc-register')
    information_locator = (By.XPATH, '//section[@id="page-left"]//child::div//child::div[2]')
    information_text_locator = (By.XPATH, '//div[@class="what-is"]')
    registration_name_field_locator = (By.XPATH, '//input[@name="firstName"]//following::span')
    registration_lastname_field_locator = (By.XPATH, '//input[@name="lastName"]//following::span')
    registration_region_field_locator = (By.XPATH, '//span[@class="rt-input__placeholder rt-input__placeholder--top"]')
    registration_email_or_phone_field_locator = (By.XPATH, '//input[@id="address"]//following::span')
    registration_password_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    registration_repeat_password_field_locator = (By.XPATH, '//input[@id="password-confirm"]//following::span')
    registration_button_locator = (
    By.XPATH, '//button[@class="rt-btn rt-btn--orange rt-btn--medium rt-btn--rounded register-form__reg-btn"]')
    forgot_password_link_locator = (By.XPATH, '//a[@id="forgot_password"]')
    captcha_field_locator = (By.XPATH, '//input[@id="captcha"]//following::span')
    reset_button_locator = (By.XPATH, '//button[@id="reset"]')
    come_back_button_locator = (By.XPATH, '//button[@id="reset-back"]')
    password_text_field_locator = (By.CSS_SELECTOR,
                                   '.rt-input.rt-input--rounded.rt-input--orange.rt-input--actions .rt-input__mask .rt-input__mask-start')
    error_message_locator = (By.ID, 'form-error-message')
    forgot_password_orange_link_locator = (By.XPATH,
                                           '//a[@class="rt-link rt-link--orange login-form__forgot-pwd login-form__forgot-pwd--animated"]')
    email_field_locator = (By.XPATH, '//input[@id="username"]')
    password_field_locator = (By.XPATH, '//input[@id="password"]')
    error_email_pass_message_locator = (By.XPATH,
                                        '//span[@class="rt-input-container__meta rt-input-container__meta--error"]')
    login_text_field_locator = (By.XPATH, '//input[@name="username"]')


class OnlimeSearchLocator:
    go_with_password_button_locator = (By.XPATH, '//button[@id="standard_auth_btn"]')
    header_child_locator = (By.XPATH, '//header[@id="app-header"]//child::div//child::div')
    logo_locator = (By.XPATH, '//div[@class="main-header__logo-container"]')
    phone_tab_locator = (By.ID, 't-btn-tab-phone')
    email_tab_locator = (By.ID, 't-btn-tab-mail')
    login_tab_locator = (By.ID, 't-btn-tab-login')
    phone_field_locator = (By.XPATH, '//input[@id="username"]//following::span')
    password_name_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    login_button_locator = (By.XPATH, '//button[@id="kc-login"]')
    login_otp_button_locator = (By.XPATH, '//button[@id="back_to_otp_btn"]')
    user_agreement_link_locator = (By.XPATH, '//div[@class="auth-policy"]//child::a')
    information_locator = (By.XPATH, '//section[@id="page-left"]//child::div//child::div[2]')
    information_text_locator = (By.XPATH, '//div[@class="what-is"]')
    login_field_text_locator = (By.XPATH, '//input[@id="address"]//following::span')
    otp_get_code_button_locator = (By.XPATH, '//button[@id="otp_get_code"]')
    forgot_password_link_locator = (By.XPATH, '//a[@id="forgot_password"]')
    personal_account_tab_locator = (By.ID, 't-btn-tab-ls')
    captcha_field_locator = (By.XPATH, '//input[@id="captcha"]//following::span')
    reset_button_locator = (By.XPATH, '//button[@id="reset"]')
    come_back_button_locator = (By.XPATH, '//button[@id="reset-back"]')


class StartSearchLocator:
    go_with_password_button_locator = (By.XPATH, '//button[@id="standard_auth_btn"]')
    header_child_locator = (By.XPATH, '//header[@id="app-header"]//child::div//child::div')
    logo_locator = (By.XPATH, '//div[@class="main-header__logo-container"]')
    email_tab_locator = (By.ID, 't-btn-tab-mail')
    login_tab_locator = (By.ID, 't-btn-tab-login')
    phone_tab_locator = (By.ID, 't-btn-tab-phone')
    personal_account_tab_locator = (By.ID, 't-btn-tab-ls')
    phone_field_locator = (By.XPATH, '//input[@id="username"]//following::span')
    password_name_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    login_button_locator = (By.XPATH, '//button[@id="kc-login"]')
    login_otp_button_locator = (By.XPATH, '//button[@id="back_to_otp_btn"]')
    user_agreement_link_locator = (By.XPATH, '//div[@class="auth-policy"]//child::a')
    information_locator = (By.XPATH, '//section[@id="page-left"]//child::div//child::div[2]')
    information_text_locator = (By.XPATH, '//div[@class="what-is"]')
    login_field_text_locator = (By.XPATH, '//input[@id="address"]//following::span')
    otp_get_code_button_locator = (By.XPATH, '//button[@id="otp_get_code"]')
    registration_link_locator = (By.ID, 'kc-register')
    registration_name_field_locator = (By.XPATH, '//input[@name="firstName"]//following::span')
    registration_lastname_field_locator = (By.XPATH, '//input[@name="lastName"]//following::span')
    registration_region_field_locator = (By.XPATH, '//span[@class="rt-input__placeholder rt-input__placeholder--top"]')
    registration_email_or_phone_field_locator = (By.XPATH, '//input[@id="address"]//following::span')
    registration_password_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    registration_repeat_password_field_locator = (By.XPATH, '//input[@id="password-confirm"]//following::span')
    registration_button_locator = (
    By.XPATH, '//button[@class="rt-btn rt-btn--orange rt-btn--medium rt-btn--rounded register-form__reg-btn"]')
    forgot_password_link_locator = (By.XPATH, '//a[@id="forgot_password"]')
    captcha_field_locator = (By.XPATH, '//input[@id="captcha"]//following::span')
    reset_button_locator = (By.XPATH, '//button[@id="reset"]')
    come_back_button_locator = (By.XPATH, '//button[@id="reset-back"]')


class SmartHomeSearchLocator:
    go_with_password_button_locator = (By.XPATH, '//button[@id="standard_auth_btn"]')
    logo_text_locator = (By.XPATH, '//span[@class="smarthome-header__title"]')
    header_child_locator = (By.XPATH, '//header[@id="app-header"]//child::div//child::div')
    logo_locator = (By.XPATH, '//div[@class="main-header__logo-container"]')
    email_tab_locator = (By.ID, 't-btn-tab-mail')
    login_tab_locator = (By.ID, 't-btn-tab-login')
    phone_tab_locator = (By.ID, 't-btn-tab-phone')
    phone_field_locator = (By.XPATH, '//input[@id="username"]//following::span')
    password_name_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    login_button_locator = (By.XPATH, '//button[@id="kc-login"]')
    login_otp_button_locator = (By.XPATH, '//button[@id="back_to_otp_btn"]')
    user_agreement_link_locator = (By.XPATH, '//div[@class="auth-policy"]//child::a')
    registration_link_locator = (By.ID, 'kc-register')
    information_locator = (By.XPATH, '//section[@id="page-left"]//child::div//child::div[2]')
    information_text_locator = (By.XPATH, '//div[@class="what-is"]')
    login_field_text_locator = (By.XPATH, '//input[@id="address"]//following::span')
    otp_get_code_button_locator = (By.XPATH, '//button[@id="otp_get_code"]')
    registration_name_field_locator = (By.XPATH, '//input[@name="firstName"]//following::span')
    registration_lastname_field_locator = (By.XPATH, '//input[@name="lastName"]//following::span')
    registration_region_field_locator = (By.XPATH, '//span[@class="rt-input__placeholder rt-input__placeholder--top"]')
    registration_phone_field_locator = (By.XPATH, '//input[@id="address"]//following::span')
    registration_password_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    registration_repeat_password_field_locator = (By.XPATH, '//input[@id="password-confirm"]//following::span')
    registration_button_locator = (
        By.XPATH, '//button[@class="rt-btn rt-btn--blue rt-btn--medium rt-btn--rounded register-form__reg-btn"]')
    forgot_password_link_locator = (By.XPATH, '//a[@id="forgot_password"]')
    captcha_field_locator = (By.XPATH, '//input[@id="captcha"]//following::span')
    reset_button_locator = (By.XPATH, '//button[@id="reset"]')
    come_back_button_locator = (By.XPATH, '//button[@id="reset-back"]')
    personal_account_tab_locator = (By.ID, 't-btn-tab-ls')

class KeySearchLocator:
    go_to_cabinet_link_locator = (By.XPATH, '//a[@class="go_kab"]')
    go_with_password_button_locator = (By.XPATH, '//button[@id="standard_auth_btn"]')
    header_child_locator = (By.XPATH, '//header[@id="app-header"]//child::div//child::div')
    logo_locator = (By.XPATH, '//div[@class="main-header__logo-container"]')
    logo_text_locator = (By.XPATH, '//span[@class="dmh-header__title"]')
    email_tab_locator = (By.ID, 't-btn-tab-mail')
    login_tab_locator = (By.ID, 't-btn-tab-login')
    phone_tab_locator = (By.ID, 't-btn-tab-phone')
    phone_field_locator = (By.XPATH, '//input[@id="username"]//following::span')
    password_name_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    login_button_locator = (By.XPATH, '//button[@id="kc-login"]')
    login_otp_button_locator = (By.XPATH, '//button[@id="back_to_otp_btn"]')
    user_agreement_link_locator = (By.XPATH, '//div[@class="auth-policy"]//child::a')
    registration_link_locator = (By.ID, 'kc-register')
    information_locator = (By.XPATH, '//section[@id="page-left"]//child::div//child::div[2]')
    information_text_locator = (By.XPATH, '//div[@class="what-is"]')
    login_field_text_locator = (By.XPATH, '//input[@id="address"]//following::span')
    otp_get_code_button_locator = (By.XPATH, '//button[@id="otp_get_code"]')
    registration_name_field_locator = (By.XPATH, '//input[@name="firstName"]//following::span')
    registration_lastname_field_locator = (By.XPATH, '//input[@name="lastName"]//following::span')
    registration_region_field_locator = (By.XPATH, '//span[@class="rt-input__placeholder rt-input__placeholder--top"]')
    registration_email_or_phone_field_locator = (By.XPATH, '//input[@id="address"]//following::span')
    registration_password_field_locator = (By.XPATH, '//input[@id="password"]//following::span')
    registration_repeat_password_field_locator = (By.XPATH, '//input[@id="password-confirm"]//following::span')
    registration_button_locator = (
        By.XPATH, '//button[@class="rt-btn rt-btn--purple rt-btn--medium rt-btn--rounded register-form__reg-btn"]')
    forgot_password_link_locator = (By.XPATH, '//a[@id="forgot_password"]')
    captcha_field_locator = (By.XPATH, '//input[@id="captcha"]//following::span')
    reset_button_locator = (By.XPATH, '//button[@id="reset"]')
    come_back_button_locator = (By.XPATH, '//button[@id="reset-back"]')
    personal_account_tab_locator = (By.ID, 't-btn-tab-ls')
